pub const State = enum {
    Done,
    ReadAttributes,
    ReadClosingComment,
    ReadDoctype,
    ReadClosingCommentDash,
    ReadClosingTagName,
    ReadCommentContent,
    ReadContent,
    ReadOpeningCommentDash,
    ReadOpeningCommentOrDoctype,
    ReadOpeningTagName,
    ReadTagName,
    ReadText,
    SeekOpeningTag,
};
